version: '2'
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./:/etc/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    #restart: always
